CREATE TABLE SALES (
  Date TEXT PRIMARY KEY,
  Order_id TEXT NOT NULL,
  Item_id TEXT NOT NULL,
  Customer_id TEXT NOT NULL,
  Quantity TEXT NOT NULL,
  Revenue TEXT NOT NULL
);

CREATE TABLE ITEMS (
  Item_id TEXT PRIMARY KEY,
  Item_name TEXT NOT NULL,
  price INT NOT NULL,
  department TEXT NOT NULL
);

CREATE TABLE CUSTOMERS (
  customer_id TEXT PRIMARY KEY,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  Address TEXT NOT NULL
);

-- SALES – Date, Order_id, Item_id, Customer_id, Quantity, Revenue

-- ITEMS – Item_id, Item_name, price, department

-- CUSTOMERS- customer_id, first_name,last_name,Address
    
-- insert some values
INSERT INTO SALES VALUES ("18th March 2023", "12345", "5674", "1", "3", "10");

INSERT INTO ITEMS VALUES ("5674", "Box", 20, "Furniture");

INSERT INTO CUSTOMERS VALUES ("1", "John", "Doe", "123");



-- Pull total number of orders that were completed on 18th March 2023 with the first name ‘John’ and last name Doe’
SET @q1 = (select Customer_id from SALES where Date = "18th March 2023")

SELECT * FROM Customers WHERE customer_id IN q1 and first_name == "John" and lst_name == "Doe";

-- Pull total number of customers that purchased in January 2023 and the average amount spend per customer
SET @q2 = (select Revenue from SALES where "January 2023" in Date)
SET @totalcustomers = LEN(q2)
SET @avgrevenue = SUM(q2)/totalcustomers

-- Pull the departments that generated less than $600 in 2022
SET q3 = (select department from ITEMS where price < 600)


-- What is the most and least revenue we have generated by an order
SET allprices = select price from SALES
SET maxRevenue = SELECT MIN(allprices)
SET maxRevenue = SELECT MAX(allprices)


-- What were the orders that were purchased in our most lucrative order
SET largestOrder = (select * from SALES where price == maxRevenue)
